# Prometheus OS GDM Configuration
[daemon]
WaylandEnable=true
DefaultSession=prometheus-gnome.desktop
InitialSetupEnable=false
AutomaticLoginEnable=false

[security]
AllowRoot=false
DisallowTCP=true

[chooser]
AllowRemote=true

[debug]
Enable=false

[servicemanager]
UserService=gdm.service
