[Icon Theme]
Name=Prometheus-Icons
Comment=Prometheus OS Icon Theme
Example=folder
Hidden=false

[Desktop Entry]
Type=X-GNOME-IconTheme
Name=Prometheus-Icons
Comment=Prometheus OS Icon Theme

Directories=scalable/apps,scalable/actions,scalable/devices,scalable/status,symbolic/apps,symbolic/actions

[scalable/apps]
Size=48
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[scalable/actions]
Size=48
Context=Actions
Type=Scalable

[scalable/devices]
Size=48
Context=Devices
Type=Scalable

[scalable/status]
Size=48
Context=Status
Type=Scalable

[symbolic/apps]
Size=16
MinSize=16
MaxSize=16
Context=Applications
Type=Scalable

[symbolic/actions]
Size=16
Context=Actions
Type=Scalable
